import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import "@stride/ui/styles";
import { CommandPaletteProvider } from "@/components/CommandPaletteProvider";
import { ErrorSuppressor } from "./components/ErrorSuppressor";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans antialiased bg-background dark:bg-background-dark`}
      >
        <ErrorSuppressor />
        <CommandPaletteProvider>{children}</CommandPaletteProvider>
        <Toaster
          position="bottom-right"
          toastOptions={{
            classNames: {
              toast: 'bg-background-secondary dark:bg-background-dark-secondary border border-border dark:border-border-dark text-foreground dark:text-foreground-dark',
              title: 'text-foreground dark:text-foreground-dark font-medium',
              description: 'text-foreground-secondary dark:text-foreground-dark-secondary text-sm',
              success: 'border-success dark:border-success-dark',
              error: 'border-error dark:border-error-dark',
              warning: 'border-warning dark:border-warning-dark',
              info: 'border-info dark:border-info-dark',
            },
          }}
        />
      </body>
    </html>
  );
}
