// Re-export Prisma types directly from @prisma/client
// Note: Prisma client must be generated by @stride/database package before building
// The database package's build script runs prisma generate, which makes types available here
export type {
  User as PrismaUser,
  Project as PrismaProject,
  Issue as PrismaIssue,
  Cycle as PrismaCycle,
  Comment as PrismaComment,
  Attachment as PrismaAttachment,
  RepositoryConnection as PrismaRepositoryConnection,
  IssueBranch as PrismaIssueBranch,
  Webhook as PrismaWebhook,
  Session as PrismaSession,
} from '@prisma/client';

